-- Saved "Laporan" (reports) generated by a School PIC via the report-builder. Each row is
-- a snapshot of already-real, already-computed school data at generation time (student
-- performance/ranking, tryout participation, or PTN target analysis) — re-opening an old
-- report shows exactly what was true when it was generated, not a live recomputation.

CREATE TABLE school_reports (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    school_id    UUID NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    report_type  TEXT NOT NULL,
    title        TEXT NOT NULL,
    period_label TEXT NOT NULL,
    class_filter TEXT,
    payload      JSONB NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_school_reports_school ON school_reports (school_id, created_at DESC);
